name: CI

on:
  push:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-python3.6

    steps:
    - name: Run
      run: |
        mkdir -p /github/home/.cache/pip
        python -V
        pip install --upgrade pip
        pip install six
        echo pip cache dir: $(pip cache dir)
