name: CI

on:
  push:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-python3.6

    steps:
    - name: Run
      run: |
        python -V
        pip install --upgrade pip
        pip install six
        env
        ls -l
        ls -l /
        ls -l /github
