name: CI

on:
  push:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-python3.6

    steps:
    - name: Run
      run: |
        set -x
        python -V
        pip install --upgrade pip
        pip install six
        id
        stat /github
        ls -l /github
        ls -l /github/home
        ls -l /github/home/.cache
        ls -l /github/home/.cache/pip
