name: CI

on:
  push:
    branches: [ master ]    

jobs:
  build:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-python3.6

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - run: ls -l ~/.ssh
      - run: cat ~/.ssh/known_hosts
      - run: |
          #ssh-keyscan github.com >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      - run: git clone git@github.com:kaltura/datalake-etl.git
      - name: Run
        run: |
          mkdir -p ~/.cache/pip
          pip install --upgrade pip
          pip install six
